FROM scratch
COPY static/io/zonky/test/postgres/index.html /io/zonky/test/postgres/index.html
COPY static/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/index.html /io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/index.html
COPY static/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64-alpine/index.html /io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64-alpine/index.html
COPY static/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64-alpine/15.3.0/index.html /io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64-alpine/15.3.0/index.html
COPY static/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64-alpine/15.3.0/embedded-postgres-binaries-linux-amd64-alpine-15.3.0.jar /io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64-alpine/15.3.0/embedded-postgres-binaries-linux-amd64-alpine-15.3.0.jar
COPY static/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64-alpine/14.8.0/index.html /io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64-alpine/14.8.0/index.html
COPY static/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64-alpine/14.8.0/embedded-postgres-binaries-linux-amd64-alpine-14.8.0.jar /io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64-alpine/14.8.0/embedded-postgres-binaries-linux-amd64-alpine-14.8.0.jar
COPY static/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64-alpine/13.11.0/index.html /io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64-alpine/13.11.0/index.html
COPY static/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64-alpine/13.11.0/embedded-postgres-binaries-linux-amd64-alpine-13.11.0.jar /io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64-alpine/13.11.0/embedded-postgres-binaries-linux-amd64-alpine-13.11.0.jar
COPY static/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64-alpine/12.15.0/index.html /io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64-alpine/12.15.0/index.html
COPY static/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64-alpine/12.15.0/embedded-postgres-binaries-linux-amd64-alpine-12.15.0.jar /io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64-alpine/12.15.0/embedded-postgres-binaries-linux-amd64-alpine-12.15.0.jar
COPY static/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/15.3.0/index.html /io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/15.3.0/index.html
COPY static/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/15.3.0/embedded-postgres-binaries-linux-amd64-15.3.0.jar /io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/15.3.0/embedded-postgres-binaries-linux-amd64-15.3.0.jar
COPY static/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/14.8.0/index.html /io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/14.8.0/index.html
COPY static/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/14.8.0/embedded-postgres-binaries-linux-amd64-14.8.0.jar /io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/14.8.0/embedded-postgres-binaries-linux-amd64-14.8.0.jar
COPY static/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/13.11.0/index.html /io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/13.11.0/index.html
COPY static/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/13.11.0/embedded-postgres-binaries-linux-amd64-13.11.0.jar /io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/13.11.0/embedded-postgres-binaries-linux-amd64-13.11.0.jar
COPY static/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/12.15.0/index.html /io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/12.15.0/index.html
COPY static/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/12.15.0/embedded-postgres-binaries-linux-amd64-12.15.0.jar /io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/12.15.0/embedded-postgres-binaries-linux-amd64-12.15.0.jar
COPY static/io/zonky/test/index.html /io/zonky/test/index.html
COPY static/io/zonky/index.html /io/zonky/index.html
COPY static/io/index.html /io/index.html
COPY static/index.html /index.html
